# This file was generated by GoReleaser. DO NOT EDIT.
cask "agent-ops" do
  version "0.5.7"

  on_macos do
    on_intel do
      sha256 "0669e208f42df5604aa3f7e49e664cfb8ed6e9d5dd2373566c57ec6fe621e78f"
      url "https://dl.zibby.app/agent-ops/v#{version}/agent-ops_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "45e181f83703e3d14e59c746778ca4bf47bb955a386a167a024c2be40ebde411"
      url "https://dl.zibby.app/agent-ops/v#{version}/agent-ops_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a85ce3e44953f05be38fbb111a2849ac5786954587c9c045f4d602249e2416fe"
      url "https://dl.zibby.app/agent-ops/v#{version}/agent-ops_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9c95ca70559dfea79ee67f1dcb12a7efbe1bbf91d16b767919587638b8499ace"
      url "https://dl.zibby.app/agent-ops/v#{version}/agent-ops_linux_arm64.tar.gz"
    end
  end

  name "agent-ops"
  desc "Autonomous DevOps engineer for a single host."
  homepage "https://github.com/ZibbyHQ/agent-ops"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agent-ops"
  binary "agent-opsd"

  # No zap stanza required

end
