# This file was generated by GoReleaser. DO NOT EDIT.
cask "agent-ops" do
  version "0.5.9"

  on_macos do
    on_intel do
      sha256 "4bf5dd536f34ae6d215d95bcfe7203a43606daa921fed1d6bc701619e3d5e0f3"
      url "https://dl.zibby.app/agent-ops/v#{version}/agent-ops_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4041523f5ca4eaf32251d8b20e8987415057463654003e44520e151c967b63db"
      url "https://dl.zibby.app/agent-ops/v#{version}/agent-ops_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2033deecc459ff66a57d643f1a70c9712a619fba9b6d4bb27a6e6f9590002c8f"
      url "https://dl.zibby.app/agent-ops/v#{version}/agent-ops_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "81af1c398a75c7b04fc8dc276456763cf57a38314bd06a515b13a8a583a1ef20"
      url "https://dl.zibby.app/agent-ops/v#{version}/agent-ops_linux_arm64.tar.gz"
    end
  end

  name "agent-ops"
  desc "Autonomous DevOps engineer for a single host."
  homepage "https://github.com/ZibbyHQ/agent-ops"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agent-ops"
  binary "agent-opsd"

  # No zap stanza required

end
