# This file was generated by GoReleaser. DO NOT EDIT.
cask "agent-ops" do
  version "0.5.9"

  on_macos do
    on_intel do
      sha256 "96d5f2a408d8e911fa60c735dad57b3c62991aebf227c37467f9fcceaf460dc2"
      url "https://dl.zibby.app/agent-ops/v#{version}/agent-ops_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c32b953e7c5914d95ce2706f40e4bcbbc65bdcd0e6e9a2b49aea7c78de4b3684"
      url "https://dl.zibby.app/agent-ops/v#{version}/agent-ops_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "114fd72f2f5b43721dddbd3054351285dc5db1269dafcfd424557a1dbf5690b6"
      url "https://dl.zibby.app/agent-ops/v#{version}/agent-ops_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0c679463ed55f96fe594ca8a3c0a6141b84ffedc975e74bfe7bd1cd0711d7e9d"
      url "https://dl.zibby.app/agent-ops/v#{version}/agent-ops_linux_arm64.tar.gz"
    end
  end

  name "agent-ops"
  desc "Autonomous DevOps engineer for a single host."
  homepage "https://github.com/ZibbyHQ/agent-ops"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agent-ops"
  binary "agent-opsd"

  # No zap stanza required

end
